INSERT INTO TitiushkoStatus([Name],[Description],[DateCreated],[DateModified],[UserCreated],[UserModified]) VALUES
('Malesuada Id Ltd','Apartado núm.: 404, 6887 Mi Calle',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Shana','Christen'),
('Luctus Aliquet Odio Ltd','984-7575 Vulputate Calle',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Matthew','Tana'),
('Sed Pede Cum Ltd','Apartado núm.: 804, 6960 Orci, Calle',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Branden','Chanda'),
('Ipsum Primis Associates','Apdo.:441-1801 Quam Av.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Stone','Colby'),
('Semper Nam PC','640-9575 Aliquet, Calle',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Aubrey','Kimberly'),
('Erat Eget Tincidunt Foundation','482-4471 Etiam Avda.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Tanner','Chandler'),
('Cursus Associates','Apartado núm.: 694, 6226 Euismod Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Yolanda','Kaden'),
('Molestie Pharetra Limited','447-3109 Odio, C.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Joshua','Jason'),
('Mollis Lectus Limited','9301 Lacinia. Av.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Maxwell','Hedy'),
('Urna Justo Faucibus Industries','1924 Integer Ctra.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Kirk','Timothy'),
('Lorem LLC','676-6023 Egestas. ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Richard','Vladimir'),
('Non Bibendum Sed LLP','Apdo.:183-8447 Montes, ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Oren','Thomas'),
('Lobortis Nisi Nibh Ltd','2023 Eget Ctra.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Geoffrey','Whitney'),
('Magnis LLP','Apartado núm.: 737, 2538 Elit. C/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ruth','Edward'),
('Arcu LLP','5852 Nunc ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Tate','Eric'),
('Non Magna Nam Consulting','Apdo.:322-744 Fames Ctra.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Hoyt','Ishmael'),
('Mollis Integer Tincidunt Ltd','Apartado núm.: 155, 2978 Et, Av.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Palmer','MacKenzie'),
('Nec LLC','6899 Nisl. Avda.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Christopher','Raphael'),
('In Mi LLP','Apartado núm.: 479, 118 Arcu Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Melyssa','Gil'),
('Aliquam Auctor Velit Company','585-8996 Blandit C/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Victoria','Brynne'),
('Auctor Corporation','Apdo.:761-6942 Id, Avenida',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Macon','Ian'),
('Eget Venenatis A Consulting','923-1084 Nascetur Avda.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serina','Igor'),
('Elit LLP','273-3480 Nec ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Aladdin','Ria'),
('Et Eros Company','3943 Fusce ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Sopoline','Odessa'),
('Auctor Odio A Ltd','8888 Mus. Calle',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Abra','September'),
('Consectetuer LLC','3425 Eu Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Rigel','Aretha'),
('Et Nunc Quisque Corporation','5795 Suspendisse ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ori','Hadley'),
('Dictum Proin Eget Inc.','Apdo.:333-9239 Nullam Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Veda','Derek'),
('In Tincidunt Congue Consulting','Apartado núm.: 946, 4703 Hendrerit C/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Conan','Bernard'),
('Dictum Limited','700-8988 Bibendum ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Keiko','Jacqueline'),
('Nunc Pulvinar Institute','905-5966 Sollicitudin C/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Chancellor','Orlando'),
('Nostra Per Incorporated','Apdo.:726-1995 Morbi Avda.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Fritz','Porter'),
('Ipsum Corp.','152-9552 Parturient Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Carson','Bruno'),
('Lacus Corporation','Apdo.:905-4428 Eu Av.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Adele','Alec'),
('Sodales At Limited','Apdo.:616-8274 Justo. Av.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Mark','Kuame'),
('Ante Industries','Apdo.:303-1720 Aliquam Avda.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Clayton','Kasimir'),
('Fermentum Corp.','112-2239 Dictum Avenida',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Wyoming','Adele'),
('Ipsum Dolor Sit Industries','Apdo.:807-5417 Nulla. Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Veda','Maia'),
('Ornare LLC','Apartado núm.: 685, 9115 Donec C/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Candace','Callum'),
('At Auctor Ullamcorper Corporation','Apdo.:938-380 Praesent C/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Lacota','Jeanette'),
('Ultricies Inc.','Apartado núm.: 656, 9826 Nulla Calle',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Callie','Risa'),
('Cursus Non Egestas Incorporated','Apartado núm.: 153, 4315 Nibh Ctra.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ezekiel','Mannix'),
('Magna Suspendisse Tristique Inc.','Apartado núm.: 587, 5040 Fusce Avda.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Harrison','Evan'),
('Faucibus Orci Luctus LLP','Apartado núm.: 970, 9441 Enim. C/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Lydia','Virginia'),
('Sodales Purus In Company','Apdo.:990-6644 Neque C.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Indira','Elmo'),
('Proin Vel Arcu Incorporated','250-9077 Sed, Av.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Merrill','Ava'),
('Tincidunt Vehicula Risus Limited','Apartado núm.: 983, 495 Est, Avenida',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Stella','Bert'),
('Et Associates','9706 Cursus Av.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Beau','Connor'),
('Blandit At Foundation','Apartado núm.: 658, 1952 Laoreet Calle',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Sonya','Alan'),
('Magna Ltd','682-5494 Consectetuer C.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Nehru','Nyssa');
INSERT INTO TitiushkoStatus([Name],[Description],[DateCreated],[DateModified],[UserCreated],[UserModified]) VALUES('Eu Tempor Corp.','560-1803 Ut Calle',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ann','Aubrey'),
('Eu Elit Nulla Corp.','Apdo.:253-2505 Hendrerit C/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Sybil','Rashad'),
('Neque Vitae Limited','Apdo.:615-3851 Lorem Av.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Emi','Noble'),
('Ultrices Posuere Cubilia Associates','546-8456 Odio, Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Wang','Lane'),
('Morbi Tristique Corp.','6361 Scelerisque ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Zeph','Coby'),
('Non Lobortis Quis Associates','761-6232 At, ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ezekiel','Whilemina'),
('Nibh Dolor Nonummy LLC','Apartado núm.: 389, 5690 Laoreet, C.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Zachery','Bryar'),
('Sit Amet Associates','4729 Phasellus C/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ivana','Jeanette'),
('Euismod Enim PC','Apdo.:708-7250 Enim Avenida',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Norman','Calvin'),
('Vitae Incorporated','Apartado núm.: 564, 4573 Risus Avda.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Fletcher','Malik'),
('Non Arcu Ltd','360-4933 Adipiscing Ctra.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Warren','Tarik'),
('Egestas Hendrerit Neque Corp.','Apartado núm.: 617, 6716 Lorem Calle',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Alec','Sopoline'),
('Et Lacinia Vitae LLC','857-4490 Pellentesque ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Nina','Kaseem'),
('Non Justo Proin Inc.','9520 Nibh. Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Jillian','Adara'),
('Facilisis Magna Associates','Apartado núm.: 534, 7762 Nam Av.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Orli','Ahmed'),
('Pede Blandit Congue Ltd','2861 Penatibus Avda.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Diana','Kieran'),
('Congue Turpis LLP','Apartado núm.: 508, 1354 Tincidunt Avenida',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Chancellor','Helen'),
('Sapien Nunc LLP','779-3195 Donec ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Sasha','Alma'),
('Egestas Corp.','Apdo.:775-1258 Ornare Calle',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Azalia','Ethan'),
('Luctus Et Ultrices Limited','Apartado núm.: 957, 2226 Phasellus C.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ariana','Charissa'),
('Sodales Elit Erat LLP','Apartado núm.: 661, 1454 Ac C.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'John','Neve'),
('Consectetuer Mauris Corporation','328-9066 Ornare Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Evelyn','Connor'),
('Parturient Montes Nascetur Inc.','9917 Tristique Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Larissa','Nita'),
('Diam At Company','3550 Vivamus Ctra.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Teegan','Anika'),
('Fringilla Associates','175-4183 Vulputate, Calle',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Abel','Lamar'),
('Lorem Ipsum Dolor Incorporated','Apdo.:622-4231 Egestas C/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Zane','Adena'),
('Hendrerit Donec Porttitor Foundation','465-1738 Curabitur C.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Shoshana','Ferris'),
('Auctor Institute','Apdo.:825-1071 Enim. Av.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Heidi','Nevada'),
('Orci Quis Associates','1204 Nisi ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Lyle','Jared'),
('Feugiat Lorem Ipsum Associates','146-6444 Magna Av.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Warren','Unity'),
('Cursus Nunc Associates','Apdo.:236-9184 Ipsum. Av.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Colton','Mariko'),
('Vivamus Rhoncus Donec Corp.','Apartado núm.: 496, 9739 Nunc C/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Noel','John'),
('Vulputate Mauris Ltd','Apartado núm.: 866, 8431 Turpis. Ctra.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Grant','Derek'),
('Ornare Sagittis Felis PC','Apartado núm.: 381, 8907 Aliquam ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Vivien','Celeste'),
('Et Company','119 Ullamcorper ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Solomon','Shelley'),
('Integer Tincidunt LLP','7167 Arcu. Ctra.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ray','Tucker'),
('Nisi Corp.','Apartado núm.: 782, 3143 Ridiculus C.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Genevieve','Logan'),
('Felis Eget Varius Foundation','7768 Eros. Ctra.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Colin','Ryder'),
('Lobortis Corp.','Apartado núm.: 256, 2790 Auctor Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ebony','Zachery'),
('A Enim Associates','Apdo.:833-5482 Sit ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Solomon','Iris'),
('Ac Metus Vitae Industries','9096 Montes, ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Raja','Malik'),
('Senectus Et Industries','Apartado núm.: 779, 5925 Aenean Ctra.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ciaran','Kay'),
('Pretium Limited','590-4261 Ac Avenida',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Slade','Angelica'),
('At Risus Corp.','3050 Suspendisse Avda.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Chastity','Claire'),
('Nibh LLC','143-3009 Libero. Avenida',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Avye','Hadassah'),
('Dolor Elit LLC','Apartado núm.: 832, 1065 Nisl C/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Kelly','Callum'),
('Convallis Ltd','8884 Adipiscing Avda.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Raven','Kirsten'),
('Suspendisse Aliquet LLP','625-7304 Diam Ctra.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Lee','Raymond'),
('Amet Dapibus Id LLC','Apdo.:997-6144 Purus Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ella','Valentine'),
('Magna Phasellus Dolor Consulting','693-3009 Sed Carretera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Arden','Melanie');
