//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titiushko.MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectFollowingEntities : DbContext
    {
        public ProjectFollowingEntities()
            : base("name=ProjectFollowingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<TitiushkoAssignments> TitiushkoAssignments { get; set; }
        public virtual DbSet<TitiushkoProject> TitiushkoProject { get; set; }
        public virtual DbSet<TitiushkoSprint> TitiushkoSprint { get; set; }
        public virtual DbSet<TitiushkoStatus> TitiushkoStatus { get; set; }
        public virtual DbSet<TitiushkoTask> TitiushkoTask { get; set; }
        public virtual DbSet<TitiushkoTaskType> TitiushkoTaskType { get; set; }
    }
}
