//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titiushko.MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitiushkoTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TitiushkoTask()
        {
            this.TitiushkoAssignments = new HashSet<TitiushkoAssignments>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> EstimatedHours { get; set; }
        public Nullable<int> WorkedHours { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> SprintId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> TaskTypeId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string UserModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TitiushkoAssignments> TitiushkoAssignments { get; set; }
        public virtual TitiushkoProject TitiushkoProject { get; set; }
        public virtual TitiushkoSprint TitiushkoSprint { get; set; }
        public virtual TitiushkoStatus TitiushkoStatus { get; set; }
        public virtual TitiushkoTaskType TitiushkoTaskType { get; set; }
    }
}
