//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titiushko.MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitiushkoAssignments
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int TaskId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string UserModified { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual TitiushkoTask TitiushkoTask { get; set; }
    }
}
